apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
# patchesStrategicMerge:
# - |-
#   apiVersion: apps/v1
#   kind: Deployment
#   metadata:
#     name: nginx-deployment
#   spec:
#     replicas: ${replica_count}
