apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: applicaiton-prod-environment
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: application-repo
  path: ./base
  prune: true
  wait: true
  timeout: 2m
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: application-config       
      - kind: ConfigMap
        name: application-prod-config        